package cn.com.linnax.file.model;

public class Fileinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.size
     *
     * @mbggenerated
     */
    private Integer size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.depth
     *
     * @mbggenerated
     */
    private Integer depth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.changeDate
     *
     * @mbggenerated
     */
    private String changedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.createDate
     *
     * @mbggenerated
     */
    private String createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.ext
     *
     * @mbggenerated
     */
    private String ext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.path
     *
     * @mbggenerated
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.parentPath
     *
     * @mbggenerated
     */
    private String parentpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.driver
     *
     * @mbggenerated
     */
    private String driver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.isNeedCache
     *
     * @mbggenerated
     */
    private Byte isneedcache;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileinfo.isNeedIndex
     *
     * @mbggenerated
     */
    private Byte isneedindex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.id
     *
     * @return the value of fileinfo.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.id
     *
     * @param id the value for fileinfo.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.name
     *
     * @return the value of fileinfo.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.name
     *
     * @param name the value for fileinfo.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.size
     *
     * @return the value of fileinfo.size
     *
     * @mbggenerated
     */
    public Integer getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.size
     *
     * @param size the value for fileinfo.size
     *
     * @mbggenerated
     */
    public void setSize(Integer size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.depth
     *
     * @return the value of fileinfo.depth
     *
     * @mbggenerated
     */
    public Integer getDepth() {
        return depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.depth
     *
     * @param depth the value for fileinfo.depth
     *
     * @mbggenerated
     */
    public void setDepth(Integer depth) {
        this.depth = depth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.changeDate
     *
     * @return the value of fileinfo.changeDate
     *
     * @mbggenerated
     */
    public String getChangedate() {
        return changedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.changeDate
     *
     * @param changedate the value for fileinfo.changeDate
     *
     * @mbggenerated
     */
    public void setChangedate(String changedate) {
        this.changedate = changedate == null ? null : changedate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.createDate
     *
     * @return the value of fileinfo.createDate
     *
     * @mbggenerated
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.createDate
     *
     * @param createdate the value for fileinfo.createDate
     *
     * @mbggenerated
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.ext
     *
     * @return the value of fileinfo.ext
     *
     * @mbggenerated
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.ext
     *
     * @param ext the value for fileinfo.ext
     *
     * @mbggenerated
     */
    public void setExt(String ext) {
        this.ext = ext == null ? null : ext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.path
     *
     * @return the value of fileinfo.path
     *
     * @mbggenerated
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.path
     *
     * @param path the value for fileinfo.path
     *
     * @mbggenerated
     */
    public void setPath(String path) {
        this.path = path == null ? null : path.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.parentPath
     *
     * @return the value of fileinfo.parentPath
     *
     * @mbggenerated
     */
    public String getParentpath() {
        return parentpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.parentPath
     *
     * @param parentpath the value for fileinfo.parentPath
     *
     * @mbggenerated
     */
    public void setParentpath(String parentpath) {
        this.parentpath = parentpath == null ? null : parentpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.driver
     *
     * @return the value of fileinfo.driver
     *
     * @mbggenerated
     */
    public String getDriver() {
        return driver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.driver
     *
     * @param driver the value for fileinfo.driver
     *
     * @mbggenerated
     */
    public void setDriver(String driver) {
        this.driver = driver == null ? null : driver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.isNeedCache
     *
     * @return the value of fileinfo.isNeedCache
     *
     * @mbggenerated
     */
    public Byte getIsneedcache() {
        return isneedcache;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.isNeedCache
     *
     * @param isneedcache the value for fileinfo.isNeedCache
     *
     * @mbggenerated
     */
    public void setIsneedcache(Byte isneedcache) {
        this.isneedcache = isneedcache;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fileinfo.isNeedIndex
     *
     * @return the value of fileinfo.isNeedIndex
     *
     * @mbggenerated
     */
    public Byte getIsneedindex() {
        return isneedindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fileinfo.isNeedIndex
     *
     * @param isneedindex the value for fileinfo.isNeedIndex
     *
     * @mbggenerated
     */
    public void setIsneedindex(Byte isneedindex) {
        this.isneedindex = isneedindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileinfo
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", size=").append(size);
        sb.append(", depth=").append(depth);
        sb.append(", changedate=").append(changedate);
        sb.append(", createdate=").append(createdate);
        sb.append(", ext=").append(ext);
        sb.append(", path=").append(path);
        sb.append(", parentpath=").append(parentpath);
        sb.append(", driver=").append(driver);
        sb.append(", isneedcache=").append(isneedcache);
        sb.append(", isneedindex=").append(isneedindex);
        sb.append("]");
        return sb.toString();
    }
}