//package cn.com.linnax.file.model;
//
//public class XiDongWangWithBLOBs extends XiDongWang {
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column xi_dong_wang.body
//     *
//     * @mbggenerated
//     */
//    private String body;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column xi_dong_wang.attribute
//     *
//     * @mbggenerated
//     */
//    private String attribute;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column xi_dong_wang.introduction
//     *
//     * @mbggenerated
//     */
//    private String introduction;
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column xi_dong_wang.body
//     *
//     * @return the value of xi_dong_wang.body
//     *
//     * @mbggenerated
//     */
//    public String getBody() {
//        return body;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column xi_dong_wang.body
//     *
//     * @param body the value for xi_dong_wang.body
//     *
//     * @mbggenerated
//     */
//    public void setBody(String body) {
//        this.body = body == null ? null : body.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column xi_dong_wang.attribute
//     *
//     * @return the value of xi_dong_wang.attribute
//     *
//     * @mbggenerated
//     */
//    public String getAttribute() {
//        return attribute;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column xi_dong_wang.attribute
//     *
//     * @param attribute the value for xi_dong_wang.attribute
//     *
//     * @mbggenerated
//     */
//    public void setAttribute(String attribute) {
//        this.attribute = attribute == null ? null : attribute.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column xi_dong_wang.introduction
//     *
//     * @return the value of xi_dong_wang.introduction
//     *
//     * @mbggenerated
//     */
//    public String getIntroduction() {
//        return introduction;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column xi_dong_wang.introduction
//     *
//     * @param introduction the value for xi_dong_wang.introduction
//     *
//     * @mbggenerated
//     */
//    public void setIntroduction(String introduction) {
//        this.introduction = introduction == null ? null : introduction.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table xi_dong_wang
//     *
//     * @mbggenerated
//     */
//    @Override
//    public String toString() {
//        StringBuilder sb = new StringBuilder();
//        sb.append(getClass().getSimpleName());
//        sb.append(" [");
//        sb.append("Hash = ").append(hashCode());
//        sb.append(", body=").append(body);
//        sb.append(", attribute=").append(attribute);
//        sb.append(", introduction=").append(introduction);
//        sb.append("]");
//        return sb.toString();
//    }
//}