//package cn.com.linnax.file.model;
//
//public class XiDongWang {
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column xi_dong_wang.aid
//     *
//     * @mbggenerated
//     */
//    private Integer aid;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column xi_dong_wang.typeid
//     *
//     * @mbggenerated
//     */
//    private Short typeid;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column xi_dong_wang.redirecturl
//     *
//     * @mbggenerated
//     */
//    private String redirecturl;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column xi_dong_wang.templet
//     *
//     * @mbggenerated
//     */
//    private String templet;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column xi_dong_wang.userip
//     *
//     * @mbggenerated
//     */
//    private String userip;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column xi_dong_wang.download
//     *
//     * @mbggenerated
//     */
//    private String download;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column xi_dong_wang.top_nav
//     *
//     * @mbggenerated
//     */
//    private String topNav;
//
//    /**
//     * This field was generated by MyBatis Generator.
//     * This field corresponds to the database column xi_dong_wang.sub_nav
//     *
//     * @mbggenerated
//     */
//    private String subNav;
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column xi_dong_wang.aid
//     *
//     * @return the value of xi_dong_wang.aid
//     *
//     * @mbggenerated
//     */
//    public Integer getAid() {
//        return aid;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column xi_dong_wang.aid
//     *
//     * @param aid the value for xi_dong_wang.aid
//     *
//     * @mbggenerated
//     */
//    public void setAid(Integer aid) {
//        this.aid = aid;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column xi_dong_wang.typeid
//     *
//     * @return the value of xi_dong_wang.typeid
//     *
//     * @mbggenerated
//     */
//    public Short getTypeid() {
//        return typeid;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column xi_dong_wang.typeid
//     *
//     * @param typeid the value for xi_dong_wang.typeid
//     *
//     * @mbggenerated
//     */
//    public void setTypeid(Short typeid) {
//        this.typeid = typeid;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column xi_dong_wang.redirecturl
//     *
//     * @return the value of xi_dong_wang.redirecturl
//     *
//     * @mbggenerated
//     */
//    public String getRedirecturl() {
//        return redirecturl;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column xi_dong_wang.redirecturl
//     *
//     * @param redirecturl the value for xi_dong_wang.redirecturl
//     *
//     * @mbggenerated
//     */
//    public void setRedirecturl(String redirecturl) {
//        this.redirecturl = redirecturl == null ? null : redirecturl.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column xi_dong_wang.templet
//     *
//     * @return the value of xi_dong_wang.templet
//     *
//     * @mbggenerated
//     */
//    public String getTemplet() {
//        return templet;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column xi_dong_wang.templet
//     *
//     * @param templet the value for xi_dong_wang.templet
//     *
//     * @mbggenerated
//     */
//    public void setTemplet(String templet) {
//        this.templet = templet == null ? null : templet.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column xi_dong_wang.userip
//     *
//     * @return the value of xi_dong_wang.userip
//     *
//     * @mbggenerated
//     */
//    public String getUserip() {
//        return userip;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column xi_dong_wang.userip
//     *
//     * @param userip the value for xi_dong_wang.userip
//     *
//     * @mbggenerated
//     */
//    public void setUserip(String userip) {
//        this.userip = userip == null ? null : userip.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column xi_dong_wang.download
//     *
//     * @return the value of xi_dong_wang.download
//     *
//     * @mbggenerated
//     */
//    public String getDownload() {
//        return download;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column xi_dong_wang.download
//     *
//     * @param download the value for xi_dong_wang.download
//     *
//     * @mbggenerated
//     */
//    public void setDownload(String download) {
//        this.download = download == null ? null : download.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column xi_dong_wang.top_nav
//     *
//     * @return the value of xi_dong_wang.top_nav
//     *
//     * @mbggenerated
//     */
//    public String getTopNav() {
//        return topNav;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column xi_dong_wang.top_nav
//     *
//     * @param topNav the value for xi_dong_wang.top_nav
//     *
//     * @mbggenerated
//     */
//    public void setTopNav(String topNav) {
//        this.topNav = topNav == null ? null : topNav.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method returns the value of the database column xi_dong_wang.sub_nav
//     *
//     * @return the value of xi_dong_wang.sub_nav
//     *
//     * @mbggenerated
//     */
//    public String getSubNav() {
//        return subNav;
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method sets the value of the database column xi_dong_wang.sub_nav
//     *
//     * @param subNav the value for xi_dong_wang.sub_nav
//     *
//     * @mbggenerated
//     */
//    public void setSubNav(String subNav) {
//        this.subNav = subNav == null ? null : subNav.trim();
//    }
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table xi_dong_wang
//     *
//     * @mbggenerated
//     */
//    @Override
//    public String toString() {
//        StringBuilder sb = new StringBuilder();
//        sb.append(getClass().getSimpleName());
//        sb.append(" [");
//        sb.append("Hash = ").append(hashCode());
//        sb.append(", aid=").append(aid);
//        sb.append(", typeid=").append(typeid);
//        sb.append(", redirecturl=").append(redirecturl);
//        sb.append(", templet=").append(templet);
//        sb.append(", userip=").append(userip);
//        sb.append(", download=").append(download);
//        sb.append(", topNav=").append(topNav);
//        sb.append(", subNav=").append(subNav);
//        sb.append("]");
//        return sb.toString();
//    }
//}