/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_linnax_Hello */

#ifndef _Included_cn_com_linnax_Hello
#define _Included_cn_com_linnax_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_linnax_Hello
 * Method:    DisplayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_com_linnax_Hello_DisplayHello__
  (JNIEnv *, jobject);

/*
 * Class:     cn_com_linnax_Hello
 * Method:    DisplayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_com_linnax_Hello_DisplayHello__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
